### ISSUE TITLE
Plugins submitted to the plugins database must support both Mysql and Postgres based databases

### ISSUE THREAD

**Issue by danmarsden** [lavanyamanne2/moodle-local_scormcreator#10]
your sql contains mysql specific date-handling functions "FROM_UNIXTIME" - please use Moodle's userdate() helper functions and other date api functions for handling dates using php instead of within the sql - more info here:
https://moodledev.io/docs/apis/subsystems/time

**Comment by lavanyamanne2** [comment]
Updated FROM_UNIXTIME to userdate()

**Comment by danmarsden** [comment]
just spotted another mysql specific function:
https://github.com/lavanyamanne2/moodle-local_scormcreator/blob/main/classes/locallib.php#L193

**Comment by lavanyamanne2** [comment]
I couldn't see any wrong in the SQL syntax in L193. I was using get_records_sql with placeholders.

**Comment by danmarsden** [comment]
@rownum is a mysql specific function - it won't work in other database types.

**Comment by lavanyamanne2** [comment]
@rownum is updated.
