### ISSUE TITLE
please use the $CFG->tempdir location to store temp files.

### ISSUE THREAD

**Issue by danmarsden** [lavanyamanne2/moodle-local_scormcreator#11]
Moodle has a config setting called "$CFG->tempdir" that provides a temporary file storage location - many sites put this on a separate disk/ (for example to put it outside their system level backup processes)

you should really modify your code to store all the temporary files you are using in a frankenstyle named directory eg:
```
$CFG->tempdir .'/local_scormcreator/'
```

And only use that location for storing temp files - don't use things like $CFG->dataroot.'/tmp' 

hopefully that makes sense, but let me know if you need further clarification - take a look at some of the other core usages of $CFG->tempdir to get some similar examples.

**Comment by lavanyamanne2** [comment]
Yes updated $CFG->dataroot.'/tmp' to $CFG->tempdir.'/local_scormcreator/'
