### ISSUE TITLE
check if dirpath var is used?

### ISSUE THREAD

**Issue by danmarsden** [lavanyamanne2/moodle-local_scormcreator#14]
https://github.com/lavanyamanne2/moodle-local_scormcreator/blob/main/dissolve.php#L39

looks scary as a PARAM_RAW but I'm not sure that is actually used anywhere and maybe it just needs to be cleaned up/removed?

**Comment by lavanyamanne2** [comment]
I didn't mean to use PARAM_RAW in the sharing variables to the path. I forgot to clean it. Now its updated.
