### ISSUE TITLE
invalid install.xml file.

### ISSUE THREAD

**Issue by danmarsden** [lavanyamanne2/moodle-local_scormcreator#3]
The install.xml is not valid and appears to be been handwritten.

fristly - the table names are incorrect - all tables implemented within plugins should be prefixed with the plugin frankenstyle name "local_scormcreator" - please note that table names must not exceed 28 characters.

for example "sc_pageoptions" table should be more like "local_scormcreator_options"
if you used "local_scormcreator_pageoptions" that would be longer than 28 chars and would fail the guidelines.

more info on this is here:
https://moodledev.io/general/development/policies/codingstyle/frankenstyle#table-names

secondly - this needs to be fixed using the Moodle xmldb editor (under admin > development > XMLDB.) rather than handwriting the file to make sure it produces a valid install.xml file.

Please hit the "load" link for your plugin install.xml file in the moodle xmldb editor, and then make Moodle think there is an update to the file (easiest way to do this is to change the description of a table - add a full stop or something similar.) Then get XMLDB to "Save" the updated file which will remove all the old invalid xml from your file.

**Comment by lavanyamanne2** [comment]
Loaded the XML file.

**Comment by lavanyamanne2** [comment]
Let me know if there are things to update.
