### ISSUE TITLE
Please use placeholders in SQL queries.

### ISSUE THREAD

**Issue by danmarsden** [lavanyamanne2/moodle-local_scormcreator#4]
To prevent SQL injection vulnerabilities, you must use placeholders in your SQL queries 

This is invalid:
```
get_records_sql('SELECT * FROM {sc_manifest} WHERE id = '.$imsid.'');
```
This is better:
```
get_records_sql('SELECT * FROM {sc_manifest} WHERE id = ?', [$imsid]);
```
This is even better:
```
get_records('tablename', ['id' => $imsid]);
```

Please review all use of SQL queries and ensure that you do not inject sql queries into inline sql statements.
more info on this, along with Moodle's helper functions are here:
https://moodledev.io/docs/apis/core/dml

**Comment by lavanyamanne2** [comment]
Updated placeholders.
