### ISSUE TITLE
incorrect use of "recordset" instead of "records" functions.

### ISSUE THREAD

**Issue by danmarsden** [lavanyamanne2/moodle-local_scormcreator#6]
the "recordset" apis are mainly used when dealing with large amounts of data and must be "closed" after they are no longer required eg:

```
$largedataset = $DB->get_recordset("files", []);
foreach ($largedataset as $item) {
    // Do something.
}
$largedataset->close();
```

But - most of your code appears to be dealing with smaller data sets, so you don't need to use a recordset at all - just call the "records" version of the Moodle api function eg "get_records() or get_records_sql() - more information on recordsets vs records calls is in the dml docs here:
https://moodledev.io/docs/apis/core/dml#using-recordsets

**Comment by lavanyamanne2** [comment]
Updated recordset to records_sql
