### ISSUE TITLE
all user-facing strings need to be contained within the lang file.

### ISSUE THREAD

**Issue by danmarsden** [lavanyamanne2/moodle-local_scormcreator#8]
eg: https://github.com/lavanyamanne2/scormcreator/blob/main/edit/editmanifest.php#L128

I also saw a few others where text like "edit" was presented to the user but not in the lang file so it can't be translated.

note this is a blocker for plugins db approval.

**Comment by danmarsden** [comment]
here are some other examples:
https://github.com/lavanyamanne2/scormcreator/blob/main/dscorm.php#L77-L78

**Comment by lavanyamanne2** [comment]
Delete was translated to language string.
